version: '3'

services:
  db:
    build: ./db
    container_name: db
    environment:
      MYSQL_DATABASE: stormlight
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
      DATABASE_HOST: db
    volumes:
      - /root/nodejs/mynetwork:/var/lib/mysql
  web:
    build: ./web
    container: web
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: stormlight
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
    ports:
      - "3257:3257"
    depends_on:
      - db
    restart: on-failure 


volumes:
    nodejs_volume

networks:
    mynetwork
      driver: "bridge"
