version: '3'

services:
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: stormlight
      MYSQL_ROOT_PASSWORD: supersecret
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
      DATABASE_HOST: db
  web:
    build: ./web
    environment:
      DATABASE_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: stormlight
      MYSQL_USER: mysql
      MYSQL_PASSWORD: supersecret
    ports:
      - "3257:3257"
    depends_on:
      - db
    restart: on-failure 
